config/routes.rb
Openfoodnetwork::Application.routes.draw do
  root :to => 'home#index'

  # Redirects from old URLs avoid server errors and helps search engines
  get "/enterprises", to: redirect("/")
  get "/products", to: redirect("/")
  get "/products/:id", to: redirect("/")
  get "/t/products/:id", to: redirect("/")
  get "/about_us", to: redirect(ContentConfig.footer_about_url)

  get "/#/login", to: "home#index", as: :spree_login
  get "/login", to: redirect("/#/login")

  get "/discourse/login", to: "discourse_sso#login"
  get "/discourse/sso", to: "discourse_sso#sso"

  get "/map", to: "map#index", as: :map
  get "/sell", to: "home#sell", as: :sell

  get "/register", to: "registration#index", as: :registration
  get "/register/auth", to: "registration#authenticate", as: :registration_auth

  # Redirects to global website
  get "/connect", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/connect/")
  get "/learn", to: redirect("https://openfoodnetwork.org/#{ENV['DEFAULT_COUNTRY_CODE'].andand.downcase}/learn/")

  resource :shop, controller: "shop" do
    get :products
    post :order_cycle
    get :order_cycle
  end

  resources :producers, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :shops, only: [:index] do
    collection do
      get :signup
    end
  end

  resources :groups, only: [:index, :show] do
    collection do
      get :signup
    end
  end

  get '/checkout', :to => 'checkout#edit' , :as => :checkout
  put '/checkout', :to => 'checkout#update' , :as => :update_checkout
  get '/checkout/paypal_payment/:order_id', to: 'checkout#paypal_payment', as: :paypal_payment

  resources :enterprises do
    collection do
      post :search
      get :check_permalink
    end

    member do
      get :shop
      get :relatives
    end
  end
  get '/:id/shop', to: 'enterprises#shop', as: 'enterprise_shop'
  get "/enterprises/:permalink", to: redirect("/") # Legacy enterprise URL

  devise_for :enterprise, controllers: { confirmations: 'enterprise_confirmations' }

  namespace :admin do
    resources :order_cycles do
      post :bulk_update, on: :collection, as: :bulk_update

      member do
        get :clone
        post :notify_producers
      end
    end

    resources :enterprises do
      collection do
        get :for_order_cycle
        get :for_line_items
        post :bulk_update, as: :bulk_update
      end

      member do
        get :welcome
        put :register
      end

      resources :producer_properties do
        post :update_positions, on: :collection
      end

      resources :tag_rules, only: [:destroy]
    end

    resources :enterprise_relationships
    resources :enterprise_roles

    resources :enterprise_fees do
      collection do
        get :for_order_cycle
        post :bulk_update, :as => :bulk_update
      end
    end

    resources :enterprise_groups do
      get :move_up
      get :move_down
    end

    get '/inventory', to: 'variant_overrides#index'

    resources :variant_overrides do
      post :bulk_update, on: :collection
      post :bulk_reset, on: :collection
    end

    resources :inventory_items, only: [:create, :update]

    resources :customers, only: [:index, :create, :update, :destroy]

    resources :tag_rules, only: [], format: :json do
      get :map_by_tag, on: :collection
    end

    resource :content

    resource :accounts_and_billing_settings, only: [:edit, :update] do
      collection do
        get :show_methods
        get :start_job
      end
    end

    resource :business_model_configuration, only: [:edit, :update], controller: 'business_model_configuration'

    resource :cache_settings

    resource :account, only: [:show], controller: 'account'

    resources :column_preferences, only: [], format: :json do
      put :bulk_update, on: :collection
    end
  end

  namespace :api do
    resources :enterprises do
      post :update_image, on: :member
      get :managed, on: :collection
      get :accessible, on: :collection
    end
    resources :order_cycles do
      get :managed, on: :collection
      get :accessible, on: :collection
    end

    resource :status do
      get :job_queue
    end
  end

  namespace :open_food_network do
    resources :cart do
      post :add_variant
    end
  end

  # Mount Spree's routes
  mount Spree::Core::Engine, :at => '/'

end


# Overriding Devise routes to use our own controller
Spree::Core::Engine.routes.draw do
  devise_for :spree_user,
             :class_name => 'Spree::User',
             :controllers => { :sessions => 'spree/user_sessions',
                               :registrations => 'user_registrations',
                               :passwords => 'user_passwords' },
             :skip => [:unlocks, :omniauth_callbacks],
             :path_names => { :sign_out => 'logout' },
             :path_prefix => :user
end



Spree::Core::Engine.routes.prepend do
  match '/admin/reports/orders_and_distributors' => 'admin/reports#orders_and_distributors', :as => "orders_and_distributors_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/order_cycle_management' => 'admin/reports#order_cycle_management', :as => "order_cycle_management_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/packing' => 'admin/reports#packing', :as => "packing_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/group_buys' => 'admin/reports#group_buys', :as => "group_buys_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/bulk_coop' => 'admin/reports#bulk_coop', :as => "bulk_coop_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/payments' => 'admin/reports#payments', :as => "payments_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/orders_and_fulfillment' => 'admin/reports#orders_and_fulfillment', :as => "orders_and_fulfillment_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/users_and_enterprises' => 'admin/reports#users_and_enterprises', :as => "users_and_enterprises_admin_reports",  :via => [:get, :post]
  match '/admin/reports/sales_tax' => 'admin/reports#sales_tax', :as => "sales_tax_admin_reports",  :via  => [:get, :post]
  match '/admin/products/bulk_edit' => 'admin/products#bulk_edit', :as => "bulk_edit_admin_products"
  match '/admin/orders/bulk_management' => 'admin/orders#bulk_management', :as => "admin_bulk_order_management"
  match '/admin/reports/products_and_inventory' => 'admin/reports#products_and_inventory', :as => "products_and_inventory_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/customers' => 'admin/reports#customers', :as => "customers_admin_reports",  :via  => [:get, :post]
  match '/admin/reports/xero_invoices' => 'admin/reports#xero_invoices', :as => "xero_invoices_admin_reports",  :via  => [:get, :post]
  match '/admin', :to => 'admin/overview#index', :as => :admin
  match '/admin/payment_methods/show_provider_preferences' => 'admin/payment_methods#show_provider_preferences', :via => :get


  namespace :api, :defaults => { :format => 'json' } do
    resources :users do
      get :authorise_api, on: :collection
    end

    resources :products do
      collection do
        get :managed
        get :bulk_products
        get :overridable
      end
      delete :soft_delete

      resources :variants do
        delete :soft_delete
      end
    end

    resources :orders do
      get :managed, on: :collection
    end
  end

  namespace :admin do
    get '/search/known_users' => "search#known_users", :as => :search_known_users

    get '/search/customers' => 'search#customers', :as => :search_customers

    resources :products do
      get :product_distributions, on: :member

      post :bulk_update, :on => :collection, :as => :bulk_update
    end

    resources :orders do
      get :invoice, on: :member
      get :print, on: :member
      get :managed, on: :collection
    end

    resources :line_items, only: [:index], format: :json
  end

  resources :orders do
    get :clear, :on => :collection
    get :order_cycle_expired, :on => :collection
  end

end

app/controllers/spree/admin/orders/customer_details_controller_decorator.rb
Spree::Admin::Orders::CustomerDetailsController.class_eval do
  # Inherit CanCan permissions for the current order
  def model_class
    load_order unless @order
    @order
  end
end

app/helpers/spree/orders_helper.rb
module Spree
  module OrdersHelper
    def cart_is_empty
      order = current_order(false)
      order.nil? || order.line_items.empty?
    end

    def alternative_available_distributors(order)
      DistributionChangeValidator.new(order).available_distributors(Enterprise.all) - [order.distributor]
    end

    def last_completed_order
      spree_current_user.orders.complete.last
    end

    def cart_count
      current_order.andand.line_items.andand.count || 0
    end
  end
end

app/views/spree/admin/orders/_capture.html.haml
- # Get the payment in 'checkout' state if any, and show capture button
- if order.payments.present?
  - payment = order.payments.select{|p| p if p.state == 'checkout'}.first
  - if !payment.nil?
    - payment.actions.grep(/^capture$/).each do |action|
      - # copied from backend/app/views/spree/admin/payments/_list.html.erb
      = link_to_with_icon "icon-#{action}", t(action), fire_admin_order_payment_path(order, payment, :e => action), :method => :put, :no_text => true, :data => {:action => action}

app/views/spree/admin/orders/_invoice_table.html.haml
%table.order-summary{:width => "100%"}
  %thead
    %tr
      %th{:align => "left"}
        %h4= t(:invoice_column_item)
      %th{:align => "right", :width => "15%"}
        %h4= t(:invoice_column_qty)
      %th{:align => "right", :width => "15%"}
        %h4= @order.total_tax > 0 ? t(:invoice_column_tax) : ""
      %th{:align => "right", :width => "15%"}
        %h4= t(:invoice_column_price)
  %tbody
    - @order.line_items.sort_by{ |li| li.product.name }.each do |item|
      %tr
        %td
          = render 'spree/shared/line_item_name', line_item: item
        %td{:align => "right"}
          = item.quantity
        %td{:align => "right"}
          = item.included_tax > 0 ? item.display_included_tax : ""
        %td{:align => "right"}
          = item.display_amount_with_adjustments
    - checkout_adjustments_for(@order, exclude: [:line_item]).reject{ |a| a.amount == 0 }.reverse_each do |adjustment|
      %tr
        %td
          %strong= "#{raw(adjustment.label)}"
        %td{:align => "right"}
          1
        %td{:align => "right"}
          = adjustment.included_tax > 0 ? adjustment.display_included_tax : ""
        %td{:align => "right"}
          = adjustment.display_amount
  %tfoot
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong GST Total:
      %td{:align => "right", :colspan => "2"}
        %strong= display_checkout_tax_total(@order)
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong Total (Excl. GST):
      %td{:align => "right", :colspan => "2"}
        %strong= display_checkout_total_less_tax(@order)
    %tr
      %td{:align => "right", :colspan => "2"}
        %strong Total (Incl. GST):
      %td{:align => "right", :colspan => "2"}
        %strong= @order.display_total
%p
  &nbsp;

app/views/spree/admin/orders/bulk_management.html.haml
- content_for :app_wrapper_attrs do
  = "ng-app='admin.lineItems'"

- content_for :page_title do
  %h1.page-title
    = t("admin.orders.bulk_management.page_title")
  %a{ 'ofn-with-tip' => t("bom_tip") }
    = t("admin.whats_this")

= render :partial => 'spree/admin/shared/order_sub_menu'

= admin_inject_column_preferences module: 'admin.lineItems'

%div{ ng: { controller: 'LineItemsCtrl' } }
  %save-bar{ dirty: "bulk_order_form.$dirty", persist: "false" }
    %input.red{ type: "button", value: "Save Changes", ng: { click: "submit()", disabled: "!bulk_order_form.$dirty" } }

  .filters{ :class => "sixteen columns alpha" }
    .date_filter{ :class => "two columns alpha" }
      %label{ :for => 'start_date_filter' }
        = t("admin.start_date")
      %br
      %input{ :class => "two columns alpha", :type => "text", :id => 'start_date_filter', 'ng-model' => 'startDate', 'datepicker' => "startDate", 'confirm-change' => "confirmRefresh()", 'ng-change' => 'refreshData()' }
    .date_filter{ :class => "two columns" }
      %label{ :for => 'end_date_filter' }
        = t("admin.end_date")
      %br
      %input{ :class => "two columns alpha", :type => "text", :id => 'end_date_filter', 'ng-model' => 'endDate', 'datepicker' => "endDate", 'confirm-change' => "confirmRefresh()", 'ng-change' => 'refreshData()' }
    .one.column &nbsp;
    .filter_select{ :class => "three columns" }
      %label{ :for => 'supplier_filter' }
        = t("admin.producer")
      %br
      %select{ :class => "three columns alpha", :id => 'supplier_filter', 'select2-min-search' => 5, 'ng-model' => 'supplierFilter', 'ng-options' => 's.id as s.name for s in suppliers' }
    .filter_select{ :class => "three columns" }
      %label{ :for => 'distributor_filter' }
        = t("admin.shop")
      %br
      %select{ :class => "three columns alpha", :id => 'distributor_filter', 'select2-min-search' => 5, 'ng-model' => 'distributorFilter', 'ng-options' => 'd.id as d.name for d in distributors'}
    .filter_select{ :class => "three columns" }
      %label{ :for => 'order_cycle_filter' }
        = t("admin.order_cycle")
      %br
      %select{ :class => "three columns alpha", :id => 'order_cycle_filter', 'select2-min-search' => 5, 'ng-model' => 'orderCycleFilter', 'ng-options' => 'oc.id as oc.name for oc in orderCycles', 'confirm-change' => "confirmRefresh()", 'ng-change' => 'refreshData()'}
    .filter_clear{ :class => "two columns omega" }
      %label{ :for => 'clear_all_filters' }
      %br
      %input.red.fullwidth{ :type => 'button', :id => 'clear_all_filters', :value => "Clear All", 'ng-click' => "resetSelectFilters()" }

  %hr.divider.sixteen.columns.alpha.omega{ ng: { show: 'unitsVariantSelected()' } }

  %div.sixteen.columns.alpha.omega#group_buy_calculation{ ng: { show: 'unitsVariantSelected()' } }
    %div.shared_resource{ :class => "four columns alpha" }
      %span{ :class => 'three columns alpha' }
        %input{ type: 'checkbox', :id => 'shared_resource', 'ng-model' => 'sharedResource'}
        = t("admin.orders.bulk_management.shared")
    %div{ :class => "eight columns" }
      %h6{ :class => "eight columns alpha", 'ng-show' => 'sharedResource', style: 'text-align: center;' } {{ selectedUnitsProduct.name + ": ALL" }}
      %h6{ :class => "eight columns alpha", 'ng-hide' => 'sharedResource', style: 'text-align: center;' } {{ selectedUnitsVariant.full_name }}
    %div{ :class => "four columns omega" }
      %h6{ :class => "four columns alpha", :style => 'text-align: right;' }
        %a{ :href => '#', 'ng-click' => 'selectedUnitsVariant = {};selectedUnitsProduct = {};sharedResource=false;' } Clear
    %hr
    .row
      .one.column.alpha &nbsp;
      .two.columns
        %span.two.columns
          = t("admin.orders.bulk_management.group_buy_unit_size")
        %span.two.columns {{ formattedValueWithUnitName( selectedUnitsProduct.group_buy_unit_size, selectedUnitsProduct, selectedUnitsVariant ) }}
      .one.column &nbsp;
      .two.columns
        %span.two.columns
          = t("admin.orders.bulk_management.total_qtt_ordered")
        %span.two.columns {{ formattedValueWithUnitName( sumUnitValues(), selectedUnitsProduct, selectedUnitsVariant ) }}
      .one.column &nbsp;
      .two.columns
        %span.two.columns
          = t("admin.orders.bulk_management.max_qtt_ordered")
        %span.two.columns {{ formattedValueWithUnitName( sumMaxUnitValues(), selectedUnitsProduct, selectedUnitsVariant ) }}
      .one.column &nbsp;
      .two.columns
        %span.two.columns
          = t("admin.orders.bulk_management.current_fulfilled_units")
        %span.two.columns {{ fulfilled(sumUnitValues()) }}
      .one.column &nbsp;
      .two.columns
        %span.two.columns
          = t("admin.orders.bulk_management.max_fulfilled_units")
        %span.two.columns {{ fulfilled(sumMaxUnitValues()) }}
      .one.column.omega &nbsp;
    %div{ :class => "eight columns alpha", 'ng-hide' => 'allFinalWeightVolumesPresent()' }
      %span{ :class => "eight columns alpha", style: 'color:red' }
        = t("admin.orders.bulk_management.variants_without_unit_value")

  %hr.divider.sixteen.columns.alpha.omega

  .controls.sixteen.columns.alpha.omega{ ng: { hide: 'RequestMonitor.loading || lineItems.length == 0' } }
    %div.three.columns.alpha
      %input.fullwidth{ :type => "text", :id => 'quick_search', 'ng-model' => 'quickSearch', :placeholder => 'Quick Search' }
    = render 'admin/shared/bulk_actions_dropdown'
    %div.seven.columns &nbsp;
    %columns-dropdown{ action: "#{controller_name}_#{action_name}" }

  %div.sixteen.columns.alpha#loading{ 'ng-if' => 'RequestMonitor.loading' }
    %img.spinner{ src: "/assets/spinning-circles.svg" }
    %h1
      = t("admin.orders.bulk_management.loading")

  %div{ :class => "sixteen columns alpha", 'ng-show' => '!RequestMonitor.loading && filteredLineItems.length == 0'}
    %h1#no_results
      = t("admin.orders.bulk_management.no_results")

  .margin-bottom-50{ 'ng-hide' => 'RequestMonitor.loading || filteredLineItems.length == 0' }
    %form{ name: 'bulk_order_form' }
      %table.index#listing_orders.bulk{ :class => "sixteen columns alpha" }
        %thead
          %tr{ ng: { controller: "ColumnsCtrl" } }
            %th.bulk
              %input{ :type => "checkbox", :name => 'toggle_bulk', 'ng-click' => 'toggleAllCheckboxes()', 'ng-checked' => "allBoxesChecked()" }
            %th.order_no{ 'ng-show' => 'columns.order_no.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.number'; reverse = !reverse" }
                = t("admin.orders.bulk_management.order_no")
            %th.full_name{ 'ng-show' => 'columns.full_name.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.full_name'; reverse = !reverse" }
                = t("admin.name")
            %th.email{ 'ng-show' => 'columns.email.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.email'; reverse = !reverse" }
                = t("admin.email")
            %th.phone{ 'ng-show' => 'columns.phone.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.phone'; reverse = !reverse" }
                = t("admin.phone")
            %th.date{ 'ng-show' => 'columns.order_date.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.completed_at'; reverse = !reverse" }
                = t("admin.orders.bulk_management.order_date")
            %th.producer{ 'ng-show' => 'columns.producer.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'supplier.name'; reverse = !reverse" }
                = t("admin.producer")
            %th.order_cycle{ 'ng-show' => 'columns.order_cycle.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.order_cycle.name'; reverse = !reverse" }
                = t("admin.order_cycle")
            %th.hub{ 'ng-show' => 'columns.hub.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'order.distributor.name'; reverse = !reverse" }
                = t("admin.shop")
            %th.variant{ 'ng-show' => 'columns.variant.visible' }
              %a{ :href => '', 'ng-click' => "predicate = 'units_variant.full_name'; reverse = !reverse" }
                = t("admin.orders.bulk_management.product_unit")
            %th.quantity{ 'ng-show' => 'columns.quantity.visible' }
              = t("admin.quantity")
            %th.max{ 'ng-show' => 'columns.max.visible' }
              = t("admin.orders.bulk_management.max")
            %th.final_weight_volume{ 'ng-show' => 'columns.final_weight_volume.visible' }
              = t("admin.orders.bulk_management.weight_volume")
            %th.price{ 'ng-show' => 'columns.price.visible' }
              = t("admin.price")
            %th.actions
            %th.actions
              = t("admin.orders.bulk_management.ask")
              %input{ :type => 'checkbox', 'ng-model' => "confirmDelete" }

        %tr.line_item{ 'ng-repeat' => "line_item in filteredLineItems = ( lineItems | filter:quickSearch | selectFilter:supplierFilter:distributorFilter:orderCycleFilter | variantFilter:selectedUnitsProduct:selectedUnitsVariant:sharedResource | orderBy:predicate:reverse )", 'ng-class-even' => "'even'", 'ng-class-odd' => "'odd'", :id => "li_{{line_item.id}}" }
          %td.bulk
            %input{ :type => "checkbox", :name => 'bulk', 'ng-model' => 'line_item.checked', 'ignore-dirty' => true }
          %td.order_no{ 'ng-show' => 'columns.order_no.visible' } {{ line_item.order.number }}
          %td.full_name{ 'ng-show' => 'columns.full_name.visible' } {{ line_item.order.full_name }}
          %td.email{ 'ng-show' => 'columns.email.visible' } {{ line_item.order.email }}
          %td.phone{ 'ng-show' => 'columns.phone.visible' } {{ line_item.order.phone }}
          %td.date{ 'ng-show' => 'columns.order_date.visible' } {{ line_item.order.completed_at }}
          %td.producer{ 'ng-show' => 'columns.producer.visible' } {{ line_item.supplier.name }}
          %td.order_cycle{ 'ng-show' => 'columns.order_cycle.visible' } {{ line_item.order.order_cycle.name }}
          %td.hub{ 'ng-show' => 'columns.hub.visible' } {{ line_item.order.distributor.name }}
          %td.variant{ 'ng-show' => 'columns.variant.visible' }
            %a{ :href => '#', 'ng-click' => "setSelectedUnitsVariant(line_item.units_product,line_item.units_variant)" } {{ line_item.units_variant.full_name }}
          %td.quantity{ 'ng-show' => 'columns.quantity.visible' }
            %input.show-dirty{ :type => 'number', :name => 'quantity', :id => 'quantity', ng: { model:  "line_item.quantity", change: "updateOnQuantity(line_item)", required: "true", class: '{"update-error": line_item.errors.quantity}' }, min: 1, step: 1 }
            %span.error{ ng: { bind: 'line_item.errors.quantity' } }
          %td.max{ 'ng-show' => 'columns.max.visible' } {{ line_item.max_quantity }}
          %td.final_weight_volume{ 'ng-show' => 'columns.final_weight_volume.visible' }
            %input.show-dirty{ :type => 'number', :name => 'final_weight_volume', :id => 'final_weight_volume', ng: { model: "line_item.final_weight_volume", readonly: "unitValueLessThanZero(line_item)", change: "weightAdjustedPrice(line_item)", required: "true", class: '{"update-error": line_item.errors.final_weight_volume}' }, min: 0, 'ng-pattern' => '/[1-9]+/' }
            %span.error{ ng: { bind: 'line_item.errors.final_weight_volume' } }
          %td.price{ 'ng-show' => 'columns.price.visible' }
            %input.show-dirty{ :type => 'text', :name => 'price', :id => 'price', :ng => { value: 'line_item.price * line_item.quantity | currency', readonly: "true", class: '{"update-error": line_item.errors.price}' } }
            %span.error{ ng: { bind: 'line_item.errors.price' } }
          %td.actions
            %a{ href: "/admin/orders/{{line_item.order.number}}/edit", :class => "edit-order icon-edit no-text", 'confirm-link-click' => 'confirmRefresh()' }
          %td.actions
            %a{ 'ng-click' => "deleteLineItem(line_item)", :class => "delete-line-item icon-trash no-text" }

app/views/spree/admin/orders/edit.html.haml
= csrf_meta_tags

- content_for :page_actions do
  %li= event_links
  %li= button_link_to t(:resend), resend_admin_order_url(@order), method: :post, icon: 'icon-email'
  %li= button_link_to t(:back_to_orders_list), admin_orders_path, icon: 'icon-arrow-left'

= admin_inject_shops 'admin.orders'
= admin_inject_order_cycles

= render 'spree/admin/shared/order_tabs', current: 'Order Details'

%div{"data-hook" => "admin_order_edit_header"}
  = render 'spree/shared/error_messages', target: @order

%div{"ng-app" => "admin.orders", "ng-controller" => "ordersCtrl", "ofn-distributor-id" => @order.distributor_id, "ofn-order-cycle-id" => @order.order_cycle_id}
  = render 'add_product'

  %div{"data-hook" => "admin_order_edit_form"}
    #order-form-wrapper
      = render 'form', order: @order

- content_for :head do
  = javascript_tag 'var expand_variants = true;'

app/views/spree/admin/orders/invoice.html.haml
= wicked_pdf_stylesheet_link_tag "mail/all"


%table{:width => "100%"}
  %tbody
    %tr{ valign: "top" }
      %td{ :align => "left", colspan: 3 }
        %h6= "Issued on: #{Time.zone.now.strftime("%F")}"
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %h4
          = "TAX INVOICE: "
          = "#{@order.number}"
      %td{width: "10%" }
        &nbsp;
      %td{ :align => "right" }
        %h4= @order.order_cycle.andand.name
    %tr{ valign: "top" }
      %td{ :align => "left" }
        %strong= "From: #{@order.distributor.name}"
        - if @order.distributor.abn.present?
          %br
          = "ABN: #{@order.distributor.abn}"
        %br
        = @order.distributor.address.full_address
        %br
        = @order.distributor.email
      %td{width: "10%" }
        &nbsp;
      %td{ :align => "right" }
        %strong= "To: #{@order.ship_address.full_name}"
        - if @order.customer.code.present?
          %br
          = "Code: #{@order.customer.code}"
        %br
        = @order.ship_address.full_address
        %br
        = "#{@order.customer.email},"
        = "#{@order.bill_address.phone}"

= render 'spree/admin/orders/invoice_table'

- if @order.special_instructions.present?
  %p.callout
    %strong
      = t :customer_instructions
  %p
    %em= @order.special_instructions
  %p
    &nbsp;

= render 'spree/order_mailer/payment'

app/views/spree/admin/orders/new.html.haml
- content_for :page_title do
  = t(:new)

- content_for :page_actions do
  %li= button_link_to t(:back_to_orders_list), spree.admin_orders_path, :icon => 'icon-arrow-left'

= admin_inject_shops 'admin.orders'
= admin_inject_order_cycles

= render 'spree/admin/shared/order_tabs', :current => 'Order Details'

= csrf_meta_tags

%div{"data-hook" => "admin_order_new_header"}
  = render 'spree/shared/error_messages', :target => @order

%div{"ng-app" => "admin.orders", "ng-controller" => "ordersCtrl"}
  %div{"ng-show" => "distributionChosen()"}
    = render 'add_product'

  - unless @order.line_items.any?
    %div{"data-hook" => "admin_order_new_form"}
      #order-form-wrapper
        = render 'form'

- content_for :head do
  = javascript_tag 'var expand_variants = true;'